### ISSUE TITLE
Add legislators of the 114th congress

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/Capitol-Words#96]
http://capitolwords.org/legislator/
![screen shot 2015-01-14 at 2 08 22 pm](https://cloud.githubusercontent.com/assets/3171982/5745467/07e73efe-9bf7-11e4-8bb1-6b23d7864909.png)

**Comment by adamsbloom** [comment]
It looks to me like this task is already completed.

**Comment by nickom** [comment]
You're right! Thanks for pointing that our @adamsbloom (and @cspeisman for fixing it!)
