### ISSUE TITLE
Daily Congressional Record scrape broken?

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/Capitol-Words#97]
Last successful day is 3/6:
http://capitolwords.org/date/2015/03/
![screen shot 2015-03-17 at 12 06 27 pm](https://cloud.githubusercontent.com/assets/3171982/6691678/51f56552-cc9e-11e4-92e7-243a86d39284.png)

GPO shows more recent stuff:
http://www.gpo.gov/fdsys/browse/collection.action?collectionCode=CREC&browsePath=2015%2F03%2F03-12%5C%2F5&isCollapsed=true&leafLevelBrowse=false&ycord=6
![screen shot 2015-03-17 at 12 06 01 pm](https://cloud.githubusercontent.com/assets/3171982/6691673/4e678c44-cc9e-11e4-90a8-2507bbfdd846.png)

**Comment by Cspeisman** [comment]
Looking into this now @nickom

**Comment by nickom** [comment]
:+1: :rocket: :+1:

**Comment by Cspeisman** [comment]
Issue is fixed.  Will import other missing dates

![screen shot 2015-03-17 at 5 49 35 pm](https://cloud.githubusercontent.com/assets/1928424/6698336/2a2ef044-ccce-11e4-981e-8f82c83faca6.png)
